### ISSUE TITLE
Feature request: speech.microphone to set the preferred mic

### ISSUE THREAD

**Issue by lslunis** [talonvoice/beta#108] opened 2020-08-28 09:47 UTC
I was using the private menu API to work around this, but it now throws `ValueError: unable to create menu item`. My preferred mic is the system default, but that isn't used because of #101

**Comment by lunixbochs** [comment] 2020-10-30 19:31
duplicate of #110, try the new action and respond in that issue

**Closed as completed by lunixbochs** 2020-10-30 19:31 UTC
