### ISSUE TITLE
Eye tracking area misaligned with multiple screens on Linux

### ISSUE THREAD

**Issue by jcaw** [talonvoice/beta#87] opened 2020-07-05 09:14 UTC
On Linux, the tracked area seems to be pegged to global `(0, 0)` rather than the top left of the main screen. If a second screen causes the primary screen to be offset from `(0,0)`, the tracked area becomes misaligned. The red box shows where the eye tracker appears to be mapped to, versus the black bar for my primary screen + tracker:

![tracker misalignment](https://user-images.githubusercontent.com/40725916/86521209-93ce1980-be45-11ea-9dfa-82ee5665e899.png)

Calibrating doesn't fix it - calibration will launch on the primary monitor, but the dots are aligned with the red area (so most of them are off-screen). Moving my second screen to the bottom right (so the primary screen is at `(0,0)`) & restarting Talon allows tracking to align properly. 

From Talon, my screens:

```
>>> ui.screens()
[Screen(x=1080.0, y=547.0, size=(1920.0, 1080.0), mm=(531.0, 299.0)), Screen(x=0.0, y=0.0, size=(1080.0, 1920.0), mm=(299.0, 531.0))]
```

`ui.screens()[0]` is my primary screen.

**Comment by lunixbochs** [comment] 2020-12-13 17:52
what's ui.main_screen() in this case?

**Comment by lunixbochs** [comment] 2020-12-25 11:57
Ah, I see why this is happening. It will be fixed as part of multimonitor eye tracking / calibration at some point.

**Comment by lunixbochs** [comment] 2021-01-10 23:06
Closing as a dupe of the newer https://github.com/talonvoice/talon/issues/202

**Closed as completed by lunixbochs** 2021-01-10 23:06 UTC
Labels: bug
