### ISSUE TITLE
Format string type checking bugs

### ISSUE THREAD

**Issue by mirober** [talonvoice/beta#68] opened 2020-05-30 15:47 UTC
Last update seems to have fixed the error I was getting but produced a new one. Feel free to ignore if you are waiting to reimplement format strings - nothing is actually broken it's just spamming the log.

Command:
```
[{direction_modifiers}] {directions} <user.n20>:
    direction_modifiers = direction_modifiers or ""
    key("{direction_modifiers}{directions}:{n20}")
```

Error when I don't say a modifier:
```
2020-05-30 16:46:02 ERROR failed to type check script
   40:            <stdlib>/threading.py:890| 
   39:            <stdlib>/threading.py:926| 
   38:            <stdlib>/threading.py:870| 
   37:                    talon\cron.py:112| 
   36: ------------------------------------# cron thread
   35:                    talon\cron.py:77 | 
   34:          talon\scripting\rctx.py:199| 
   33: ------------------------------------# 'cron' talon_plugins.engines.dragon:<lambda>()
   32:      talon\scripting\dispatch.py:92 | 
   31:      talon\scripting\dispatch.py:98 | 
   30:      talon\scripting\dispatch.py:133| 
   29:      talon\scripting\dispatch.py:124| 
   28:          talon\scripting\rctx.py:199| 
   27: ------------------------------------# 'phrase' talon_plugins.engines.dragon:_redispatch()
   26: talon\scripting\speech_system.py:42 | 
   25:      talon\scripting\dispatch.py:98 | 
   24:      talon\scripting\dispatch.py:133| 
   23:      talon\scripting\dispatch.py:124| 
   22:          talon\scripting\rctx.py:199| 
   21: ------------------------------------# 'phrase' talon_plugins.engines.dragon:engine_event()
   20: talon\scripting\speech_system.py:274| 
   19:       talon\scripting\actions.py:56 | 
   18:         talon\scripting\types.py:249| 
   17:          talon\scripting\core.py:84 | 
   16:       talon\scripting\actions.py:56 | 
   15:         talon\scripting\types.py:249| 
   14:          talon\scripting\core.py:106| 
   13:       talon\scripting\actions.py:56 | 
   12:         talon\scripting\types.py:249| 
   11:          talon\scripting\core.py:125| 
   10:       talon\scripting\actions.py:56 | 
    9:         talon\scripting\types.py:249| 
    8:          talon\scripting\core.py:146| 
    7:  talon\scripting\talon_script.py:513| 
    6: ------------------------------------# stack splice
    5:  talon\scripting\talon_script.py:511| 
    4:  talon\scripting\talon_script.py:487| 
    3:  talon\scripting\talon_script.py:242| 
    2:  talon\scripting\talon_script.py:178| 
    1:                         <string>:1  | 
NameError: name 'direction_modifiers' is not defined
```

**Comment by lunixbochs** [comment] 2020-11-02 17:26
Closing as duplicate of https://github.com/talonvoice/talon/issues/144

**Closed as completed by lunixbochs** 2020-11-02 17:26 UTC
Labels: bug

**Comment by lunixbochs** [comment] 2020-11-03 04:26
This should be fixed in the next beta, evidenced by this script:
```
test:
    x = 1
    print("hello {x} etc")
```
