### ISSUE TITLE
"git fetch {text or ''}" results in a NameError

### ISSUE THREAD

**Issue by dwiel** [talonvoice/beta#119] opened 2020-09-18 17:22 UTC
For example, defining the following:
```
git fetch [<user.text>]: "git fetch {text or ''}"
```
results in this if no text follows git fetch:
``` > auto_insert("git fetch {text or ''}")
NameError: name 'text' is not defined```

**Comment by lunixbochs** [comment] 2020-11-02 17:26
Closing as duplicate of https://github.com/talonvoice/talon/issues/144

**Closed as completed by lunixbochs** 2020-11-02 17:26 UTC
Labels: bug

**Comment by lunixbochs** [comment] 2020-11-03 04:37
Fixed in next beta:
```
test [<phrase>]:
    print("hello {phrase or 'not found'} etc")
```

```
2020-11-02 20:36:35    IO DECODED ['@test']
2020-11-02 20:36:35    IO hello not found etc
2020-11-02 20:36:57    IO DECODED ['@test', 'bananas']
2020-11-02 20:36:57    IO hello bananas etc
```
