### ISSUE TITLE
[Mac] Hiding the command history imgui also hides unrelated help imgui

### ISSUE THREAD

**Issue by knausj85** [talonvoice/beta#99] opened 2020-08-15 16:01 UTC
Setup:
v1426
OS X 10.15.6
https://github.com/knausj85/knausj_talon

Steps:
1. "command history show" -- Command History imgui appears
2. "help alphabet" -- Alphabet imgui appears
3. "command history hide" -- Both Command History imgui and Alphabet Help imgui disappear
4. "help alphabet" -- does nothing, `gui_alphabet` showing flag is still true before calling show()

History imgui code:
https://github.com/knausj85/knausj_talon/blob/d762a609d264b065c165dd97109262bf2915bae4/code/history.py#L33

"command history hide" calls this:
https://github.com/knausj85/knausj_talon/blob/master/code/history.py#L55

Alphabet imgui code:
https://github.com/knausj85/knausj_talon/blob/d762a609d264b065c165dd97109262bf2915bae4/code/help.py#L66

This does not happen on Windows, from what I can tell.

**Comment by winni2k** [comment] 2020-08-16 05:52
I can reproduce this issue on MacOS 10.14.6 running talon v1426.

**Comment by winni2k** [comment] 2020-08-19 07:48
This is still an issue on version 1435.

**Comment by lunixbochs** [comment] 2020-10-30 06:35
This seems to be a Qt issue :/ I'm definitely only calling hide on the one window, and the other is still being asked to render despite not being visible.

**Comment by lunixbochs** [comment] 2020-12-20 08:58
should be fixed in next beta

**Closed as completed** 2020-12-20 09:00 UTC
Labels: bug
